### ISSUE TITLE
Problème avec les tabs

### ISSUE THREAD

**Issue by Fredxd** [boxraiser/visual-editor#2]
Hello @Grafikart.
Tout d'abord bravo et merci pour la lib qui va en aider plus d'un.

Je viens de l'essayer rapidement et je pense avoir trouvé une issue (soit sur le code ou soit sur la doc) avec le component Tabs.
Il s'avère qu'en copiant bêtement l'exemple de la doc nous avons une erreur de type `TypeError: tab.fields is not iterable`

En espérant que ceci puisse t'aider :)

**Comment by souri84** [comment]
Yes même pb ici de mon coté :/

**Comment by Grafikart** [comment]
Pouvez vous me donner le code du bloc que vous enregistré ?

**Comment by Fredxd** [comment]
Je ne sais plus ce que j'avais tester exactement mais cela devait être une syntaxe issue de celle de la doc, un peu dans ce style.

```js
Tabs({
  tabs: [
    {
      label: 'Content',
       fields: [
          Text('test1'),
          Text('test2'),
     ],
    },
    {
      label: 'Style',
      fields: [
          Text('test3)
     ],
    }
  ]
})
```

**Comment by charlie404** [comment]
Bonjour @Fredxd ,

Effectivement, il y'a une erreur dans la doc. 
Ça fonctionne comme cela :

`Tabs({
    label: 'Content',
    fields: [
        Text('test1'),
        Text('test2'),
    ],
}, {
    label: 'Style',
    fields: [
        Text('test3')
    ],
})`

**Comment by Grafikart** [comment]
Merci pour vos remarques, j'ai mis le code de la démo à jour.
