### ISSUE TITLE
Question: Ajout d'un nouveau bloc

### ISSUE THREAD

**Issue by Fredxd** [boxraiser/visual-editor#6]
Hello @Grafikart,

Quand on ajoute un nouveau bloc il s'ajoute automatiquement en haut. 
La logique (enfin tout du moins la mienne) voudrais que l'on construise une page de haut en bas et donc lorsque l'on ajoute un bloc qu'il s'ajoute en bas.

Je ne sais pas si c'est donc un bug ou si c'est une volonté de ta part ?

Merci d'avance pour la réponse.

PS: J'ai expérimenter l'éditeur et tu as fait du bon boulot  👍

**Comment by Grafikart** [comment]
C'était une volonté car cela permet de rendre le bloc ajouté visible (normalement tu as aussi un bouton dans la partie "preview") qui lui ajoute au bon endroit. On peut envisager d'avoir une option au pire pour piloter la position de l'ajout de nouveau bloc).

**Comment by Fredxd** [comment]
Ah yep c'est une bonne idée d'avoir une option 👍

**Comment by Fredxd** [comment]
Fix by #9
